services:

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=reservations'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - database-volume:/var/lib/postgresql
    networks:
      - spring-cloud-network

  kronos:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/reservations
      - JDBC_USER=myuser
      - JDBC_PASS=secret
    networks:
      - spring-cloud-network



volumes:
  database-volume:
networks:
  spring-cloud-network:
    driver: bridge
